### ISSUE TITLE
Compatibility with Hyvä CheckoutExample Module Template

### ISSUE THREAD

**Issue by dangtrinhtran** [hyva-themes/magento2-hyva-checkout-braintree#1]
Hello,

Can you please make a branch to work with [Hyvä CheckoutExample Module Template](https://github.com/hyva-themes/magento2-checkout-example) by using `@hyva/react-checkout` for all those non-resolving imports?

Thank you.

**Comment by rajeev-k-tomy** [comment]
Can you provide more details on your problem please...

As you can see here, we have already included in the alias mapping for the same: https://github.com/hyva-themes/magento2-checkout-example/blob/master/reactapp/config-overrides.js#L20

So it should not complain about it further. Make sure you use the latest example template module version or adapt the above changes to your `config.overrides.js` file.

**Comment by dangtrinhtran** [comment]
@rajeev-k-tomy I created this issue before I created a pull request, so after you merged the pull request, it works fine now. Thanks for your response.
